# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Objc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Objc

  target 'ObjcTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'AFNetworking', '~> 3.1.0'
  end

  target 'ObjcUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
